name       : trojita
version    : 0.7
release    : 2
source     :
    - https://superb-dca2.dl.sourceforge.net/project/trojita/src/trojita-0.7.tar.xz : e08da881721cafa00ecd772eaef6b99fd37d068cb703eeb532de0ed1ea0136d9
license    : GPL-2.0
component  : network.mail
summary    : A fast and efficient mail client for IMAP.
description: |
    Trojita is an email client that doesn't slow you down.  It prioritizes productivity, resource efficiency, and adoption of and adherence to open standards.  Currently, it only officially supports one IMAP account.
libsplit    : no
builddeps  :
    - pkgconfig(Qt5WebKitWidgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(gl)
    - qtkeychain-devel
    - gpgme-devel
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
