name       : trojita
version    : '0.7'
release    : 4
source     :
    - http://sourceforge.net/projects/trojita/files/src/trojita-0.7.tar.xz/download : e08da881721cafa00ecd772eaef6b99fd37d068cb703eeb532de0ed1ea0136d9
license    : GPL-2.0-or-later
component  : network.mail
summary    : A fast and efficient mail client for IMAP.
description: |
    Trojita is an email client that doesn't slow you down.  It prioritizes productivity, resource efficiency, and adoption of and adherence to open standards.  Currently, it only officially supports one IMAP account.
libsplit   : no
builddeps  :
    - pkgconfig(Qt5WebKitWidgets)
    - pkgconfig(Qt5Svg)
    - qtkeychain-devel
    - gpgme-devel
setup      : |
    %cmake_ninja -DWITH_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
